#file: noinspection UndefinedAction
name: Run Python Tests # Name of the workflow displayed on GitHub Actions tab

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Runs on pushes to the main branch
  pull_request:
    branches: [ main ] # Runs on pull requests targeting the main branch

jobs:
  test: # ID of the job
    runs-on: ubuntu-latest # Use the latest GitHub-hosted Ubuntu runner
    strategy:
      fail-fast: false # Don't cancel other jobs in the matrix if one fails
      matrix:
        # Define Python versions to test against (match your pyproject.toml support)
        python-version: ["3.11"]

    steps:
    #----------------------------------------------
    #         Set up the environment
    #----------------------------------------------
    - name: Checkout repository code
      uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Cache pip dependencies to speed up installs

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip poetry
        # Optional: Configure Poetry to not create virtualenvs if you prefer
        # poetry config virtualenvs.create false --local

    - name: Install dependencies using Poetry
      run: |
        # Installs base dependencies + 'test' group dependencies
        poetry install --with test

    #----------------------------------------------
    #              Run tests
    #----------------------------------------------
    - name: Run tests with pytest
      run: |
        poetry run pytest # Discovers and runs tests in the 'tests' directory